//
// sdram.sv — SDRAM controller for the TI-89 core
// TI-89 MiSTer Core
//
// Backs the calculator's memories with the DE10-Nano's 32MB SDRAM
// (16-bit, 4 banks x 8192 rows x 512 columns). Clock: 60 MHz.
//
// The controller internals are based on the proven MegaDrive/MacPlus
// reference design (Sorgelig's sdram controller). This replaces the
// previous custom implementation, which suffered intermittent read
// bit-errors from a fragile PLL phase-shifted SDRAM clock and negedge
// read capture. The reference design fixes this with:
//   - SDRAM_CLK as a clean 50% duty-cycle inversion of clk (generated by
//     the top level via altddio_out), not a fragile PLL phase shift.
//   - Read data captured on the posedge of clk (center of the data eye).
//   - Auto-precharge (A10=1) on every access, so no explicit precharge
//     or tRP wait state is needed.
//   - DQM derived from the address bus (A[12:11]) during the column
//     phase, so byte-lane writes work without separate DQM registers.
//
// The external interface is unchanged from the previous controller, so
// mem_ctrl, flash_ctrl, rom_loader, TI89.sv, and the testbenches need
// no changes.
//
// Memory layout (set by mem_ctrl, which owns port A):
//   byte $000000-$3FFFFF : OS image / flash window (4 MB)
//   byte $400000-$43FFFF : calculator RAM (256 KB)
//
// Two request ports:
//   Port A — CPU-side access (from mem_ctrl's arbiter): a_rd/a_wr strobes
//     latch the request; the controller pulses a_ready on completion.
//   Port B — OS image download writes (from rom_loader): buffered in a FIFO;
//     b_wait goes high when the FIFO nears full.
//
// Address mapping (word address w = byte_addr[24:1], full 32 MB):
//   bank = w[23:22], row = w[21:9] (13 bits), column = w[8:0] (9 bits)
//

module sdram (
    input         clk,         // 60 MHz master clock
    input         clk_sdram,   // 60 MHz SDRAM clock (= ~clk, from altddio_out)
    input         reset,

    // SDRAM physical interface
    output        SDRAM_CLK,
    output        SDRAM_CKE,
    output reg [12:0] SDRAM_A,
    output reg  [1:0] SDRAM_BA,
    // DQ split into in/out/OE so a sim chip model and the top level can
    // share the bidirectional line with a single driver each.
    input  [15:0] SDRAM_DQ_IN,
    output reg [15:0] SDRAM_DQ_OUT,
    output reg        SDRAM_DQ_OE,
    output        SDRAM_DQML,
    output        SDRAM_DQMH,
    output        SDRAM_nCS,
    output reg        SDRAM_nCAS,
    output reg        SDRAM_nRAS,
    output reg        SDRAM_nWE,

    // Port A: CPU / flash controller access (byte address, word aligned)
    input  [24:0] a_addr,
    input  [15:0] a_wdata,
    input         a_rd,        // One-cycle read strobe
    input         a_wr,        // One-cycle write strobe
    input         a_uds_n,     // Byte lanes (writes)
    input         a_lds_n,
    output reg [15:0] a_rdata,
    output reg    a_ready,     // One-cycle completion pulse

    // Port B: OS loader / RAM restore writes (word address)
    input  [23:0] b_addr,
    input  [15:0] b_wdata,
    input         b_wr,
    output        b_wait,      // FIFO almost full

    output reg    init_done    // SDRAM initialized, accesses allowed
);

    // =========================================================================
    // SDRAM mode register and commands (MegaDrive reference)
    // =========================================================================

    localparam RASCAS_DELAY   = 3'd2; // tRCD -> 2 cycles (33 ns @ 60 MHz >> 20 ns)
    localparam BURST_LENGTH   = 3'd0; // 0 = 1 word
    localparam ACCESS_TYPE    = 1'd0; // 0 = sequential
    localparam CAS_LATENCY    = 3'd2; // CL = 2
    localparam OP_MODE        = 2'd0; // standard operation
    localparam NO_WRITE_BURST = 1'd1; // single-word writes only

    localparam [12:0] MODE_REG = {3'b000, NO_WRITE_BURST, OP_MODE, CAS_LATENCY, ACCESS_TYPE, BURST_LENGTH};

    localparam [1:0] MODE_NORMAL = 2'b00;
    localparam [1:0] MODE_RESET  = 2'b01;
    localparam [1:0] MODE_LDM    = 2'b10;
    localparam [1:0] MODE_PRE    = 2'b11;

    localparam [2:0] CMD_NOP             = 3'b111;
    localparam [2:0] CMD_ACTIVE          = 3'b011;
    localparam [2:0] CMD_READ            = 3'b101;
    localparam [2:0] CMD_WRITE           = 3'b100;
    localparam [2:0] CMD_BURST_TERMINATE = 3'b110;
    localparam [2:0] CMD_PRECHARGE       = 3'b010;
    localparam [2:0] CMD_AUTO_REFRESH    = 3'b001;
    localparam [2:0] CMD_LOAD_MODE       = 3'b000;

    localparam [2:0] STATE_IDLE  = 3'd0;
    localparam [2:0] STATE_START = STATE_IDLE + 3'd1;
    localparam [2:0] STATE_CONT  = STATE_START + RASCAS_DELAY;
    localparam [2:0] STATE_READY = STATE_CONT + CAS_LATENCY + 3'd1;
    localparam [2:0] STATE_LAST  = STATE_READY;

    // Refresh: 8192 rows must refresh in 64 ms -> one every 7.8 us.
    // At 60 MHz (16.7 ns/cycle), 400 cycles = 6.7 us (comfortable margin).
    localparam [9:0] REF_PERIOD = 10'd400;
    localparam [9:0] REF_HALF   = 10'd200;

    // =========================================================================
    // State and request registers
    // =========================================================================

    reg  [2:0]  state;
    reg  [1:0]  mode;
    reg  [4:0]  init_cnt;    // init sequence counter
    reg  [23:0] waddr;       // word address of the access in flight
    reg  [15:0] data;        // write data
    reg         we;          // 1 = write, 0 = read
    reg  [1:0]  dqm;         // byte write mask (1 = masked)
    reg         active;      // a normal access is in flight
    reg  [1:0]  ram_req;     // bit0 = port A, bit1 = port B

    // Port A request latch (one outstanding at a time)
    reg         pa_valid;
    reg         pa_wr;
    reg  [23:0] pa_waddr;
    reg  [15:0] pa_wdata;
    reg         pa_uds_n, pa_lds_n;

    // Port B write FIFO (8 entries)
    reg  [23:0] fifo_addr [0:7];
    reg  [15:0] fifo_data [0:7];
    reg  [3:0]  fifo_wptr, fifo_rptr;
    wire [3:0]  fifo_count = fifo_wptr - fifo_rptr;
    wire        fifo_empty = (fifo_count == 4'd0);
    assign b_wait = (fifo_count >= 4'd6);

    // Refresh manager
    reg  [9:0] rfs_cnt;
    reg        rfs, rfs2;

    // Address decode for the access in flight (TI-89 mapping)
    wire [1:0]  bank   = waddr[23:22];
    wire [12:0] row    = waddr[21:9];
    wire [8:0]  column = waddr[8:0];

    // Testbench/debug visibility: the last captured read data (== a_rdata).
    wire [15:0] sdram_dq_captured = a_rdata;

    // =========================================================================
    // Port B FIFO write
    // =========================================================================

    always @(posedge clk) begin
        if (reset) begin
            fifo_wptr <= 4'd0;
        end else if (b_wr && !b_wait) begin
            fifo_addr[fifo_wptr[2:0]] <= b_addr;
            fifo_data[fifo_wptr[2:0]] <= b_wdata;
            fifo_wptr <= fifo_wptr + 4'd1;
        end
    end

    // =========================================================================
    // Access manager (MegaDrive reference)
    // =========================================================================

    always @(posedge clk) begin
        if (reset) begin
            state     <= STATE_IDLE;
            mode      <= MODE_RESET;
            init_cnt  <= 5'h1f;
            waddr     <= 24'd0;
            data      <= 16'd0;
            we        <= 1'b0;
            dqm       <= 2'b00;
            active    <= 1'b0;
            ram_req   <= 2'b00;
            rfs       <= 1'b0;
            rfs2      <= 1'b0;
            rfs_cnt   <= 10'd0;
            a_ready   <= 1'b0;
            a_rdata   <= 16'd0;
            pa_valid  <= 1'b0;
            pa_wr     <= 1'b0;
            pa_waddr  <= 24'd0;
            pa_wdata  <= 16'd0;
            pa_uds_n  <= 1'b1;
            pa_lds_n  <= 1'b1;
            init_done <= 1'b0;
        end else begin
            a_ready <= 1'b0;

            // Refresh timer (free-running)
            rfs_cnt <= rfs_cnt + 10'd1;
            if (rfs_cnt == REF_PERIOD) begin
                rfs <= 1'b1;
                rfs_cnt <= 10'd0;
            end
            if (rfs_cnt == REF_HALF) rfs2 <= 1'b1;

            // Init sequence (runs after reset, at the end of each state cycle)
            if (state == STATE_LAST) begin
                if (init_cnt != 5'd0) begin
                    init_cnt <= init_cnt - 5'd1;
                    if (init_cnt == 5'd14)     mode <= MODE_PRE;
                    else if (init_cnt == 5'd3) mode <= MODE_LDM;
                    else                       mode <= MODE_RESET;
                end else begin
                    mode <= MODE_NORMAL;
                    init_done <= 1'b1;
                end
            end

            // Latch a new port A request (one outstanding at a time)
            if ((a_rd || a_wr) && !pa_valid) begin
                pa_valid <= 1'b1;
                pa_wr    <= a_wr;
                pa_waddr <= a_addr[24:1];
                pa_wdata <= a_wdata;
                pa_uds_n <= a_uds_n;
                pa_lds_n <= a_lds_n;
            end

            // Issue a new access from the idle state
            if (state == STATE_IDLE && mode == MODE_NORMAL) begin
                if (rfs) begin
                    // Auto-refresh
                    rfs     <= 1'b0;
                    rfs2    <= 1'b0;
                    rfs_cnt <= 10'd0;
                    we      <= 1'b0;
                    dqm     <= 2'b00;
                    active  <= 1'b0;
                    ram_req <= 2'b00;
                    state   <= STATE_START;
                end else if (pa_valid) begin
                    // Port A (CPU / flash)
                    waddr    <= pa_waddr;
                    data     <= pa_wdata;
                    we       <= pa_wr;
                    dqm      <= pa_wr ? {pa_uds_n, pa_lds_n} : 2'b00;
                    active   <= 1'b1;
                    ram_req  <= 2'b01;
                    rfs      <= rfs2;
                    pa_valid <= 1'b0;
                    state    <= STATE_START;
                end else if (!fifo_empty) begin
                    // Port B (OS loader / RAM restore, full-word writes)
                    waddr     <= fifo_addr[fifo_rptr[2:0]];
                    data      <= fifo_data[fifo_rptr[2:0]];
                    we        <= 1'b1;
                    dqm       <= 2'b00;
                    active    <= 1'b1;
                    ram_req   <= 2'b10;
                    rfs       <= rfs2;
                    fifo_rptr <= fifo_rptr + 4'd1;
                    state     <= STATE_START;
                end
            end

            // Complete the access: capture read data, signal completion
            if (state == STATE_READY && active) begin
                a_rdata <= SDRAM_DQ_IN;
                active  <= 1'b0;
                ram_req <= 2'b00;
                if (ram_req[0]) a_ready <= 1'b1;
            end

            // Advance the state machine
            if (mode != MODE_NORMAL || state != STATE_IDLE) begin
                state <= state + 3'd1;
                if (state == STATE_LAST) state <= STATE_IDLE;
            end
        end
    end

    // =========================================================================
    // SDRAM command generation (MegaDrive reference)
    // =========================================================================

    always @(posedge clk) begin
        if (reset) begin
            SDRAM_BA     <= 2'b00;
            SDRAM_A      <= 13'd0;
            SDRAM_DQ_OUT <= 16'd0;
            SDRAM_DQ_OE  <= 1'b0;
            SDRAM_nRAS   <= 1'b1;
            SDRAM_nCAS   <= 1'b1;
            SDRAM_nWE    <= 1'b1;
        end else begin
            if (state == STATE_START)
                SDRAM_BA <= (mode == MODE_NORMAL) ? bank : 2'b00;

            SDRAM_DQ_OUT <= 16'd0;
            SDRAM_DQ_OE  <= 1'b0;

            casex({active, we, mode, state})
                {2'bXX, MODE_NORMAL, STATE_START}:
                    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= active ? CMD_ACTIVE : CMD_AUTO_REFRESH;
                {2'b11, MODE_NORMAL, STATE_CONT}: begin
                    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_WRITE;
                    SDRAM_DQ_OUT <= data;
                    SDRAM_DQ_OE  <= 1'b1;
                end
                // Hold the write data for a second cycle: the SDRAM latches
                // DQ one SCLK edge after sampling the WRITE command, and the
                // SCLK/clk phase offset means that edge can fall just after a
                // single-cycle drive window. Two cycles keeps DQ valid through
                // the latch edge (harmless on real hardware).
                {2'b11, MODE_NORMAL, 3'd4}: begin
                    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_NOP;
                    SDRAM_DQ_OUT <= data;
                    SDRAM_DQ_OE  <= 1'b1;
                end
                {2'b10, MODE_NORMAL, STATE_CONT}:
                    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_READ;
                {2'bXX, MODE_LDM, STATE_START}:
                    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_LOAD_MODE;
                {2'bXX, MODE_PRE, STATE_START}:
                    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_PRECHARGE;
                default:
                    {SDRAM_nRAS, SDRAM_nCAS, SDRAM_nWE} <= CMD_NOP;
            endcase

            if (mode == MODE_NORMAL) begin
                casex(state)
                    STATE_START: SDRAM_A <= row;
                    STATE_CONT:  SDRAM_A <= {dqm, 2'b10, column};
                endcase
            end else if (mode == MODE_LDM && state == STATE_START)
                SDRAM_A <= MODE_REG;
            else if (mode == MODE_PRE && state == STATE_START)
                SDRAM_A <= 13'b0010000000000; // A10=1: precharge all banks
            else
                SDRAM_A <= 13'd0;
        end
    end

    // =========================================================================
    // SDRAM pin drivers
    // =========================================================================

    assign SDRAM_CLK  = clk_sdram;
    assign SDRAM_CKE  = 1'b1;
    assign {SDRAM_DQMH, SDRAM_DQML} = SDRAM_A[12:11];
    assign SDRAM_nCS  = 1'b0;

endmodule



